exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = blueman-applet # Bluetooth
exec-once = waybar
exec-once = hyprpaper
exec-once = hyprpm reload -n # Reload all Hyprland Plugins
exec-once = elecwhat # Whatsapp
exec-once = vesktop # Discord
exec-once = fdm --hidden # Free Download Manager (Background)
exec-once = hyprctl setcursor "Catppuccin Macchiato Lavender" 24
