local V = require("variables")
local smw = require("plugins")

local mainMod = "SUPER"

hl.bind(mainMod .. " + RETURN",            hl.dsp.exec_cmd(V.terminal))
hl.bind(mainMod .. " + SHIFT + C",         hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + RETURN",    hl.dsp.exec_cmd(V.browser))
hl.bind(mainMod .. " + SHIFT + W",         hl.dsp.exec_cmd("killall waybar && waybar"))
hl.bind(mainMod .. " + SHIFT + N",         hl.dsp.exec_cmd(V.stickynotes))
hl.bind(mainMod .. " + SHIFT + F",         hl.dsp.exec_cmd("hyprctl dispatch fullscreen"))
hl.bind("ALT + F4",                        hl.dsp.exec_cmd(V.powermenu))
hl.bind(mainMod .. " + L",                 hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + M",                 hl.dsp.exec_cmd(V.logout))
hl.bind(mainMod .. " + E",                 hl.dsp.exec_cmd(V.fileManager))
hl.bind(mainMod .. " + V",                 hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + apostrophe", hl.dsp.exec_cmd(V.emoji))
hl.bind("Print",                            hl.dsp.exec_cmd(V.screenshot))
hl.bind(mainMod .. " + SHIFT + P",         hl.dsp.exec_cmd(V.screenshot))
hl.bind("ALT + SPACE",                      hl.dsp.exec_cmd(V.menu))
hl.bind("ALT + TAB",                        hl.dsp.exec_cmd("hyprctl dispatch cyclenext"))
hl.bind("CTRL + ALT + SPACE",               hl.dsp.exec_cmd(V.calc))
hl.bind(mainMod .. " + P",                 hl.dsp.window.pseudo())
--hl.bind(mainMod .. " + J", hl.dsp.exec_cmd("hyprctl dispatch togglesplit"))

hl.bind(mainMod .. " + left",              hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right",             hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",                hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",              hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + right",     smw.cycle_workspaces("+1"))
hl.bind(mainMod .. " + SHIFT + left",      smw.cycle_workspaces("-1"))
hl.bind(mainMod .. " + SHIFT + CTRL + right", smw.move_to_workspace("+1"))
hl.bind(mainMod .. " + SHIFT + CTRL + left",  smw.move_to_workspace("-1"))

hl.bind(mainMod .. " + SHIFT + S",         hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + SHIFT + D",         hl.dsp.window.move({ workspace = "+0" }))
hl.bind(mainMod .. " + S",                 hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + mouse_down",        smw.cycle_workspaces("-1"))
hl.bind(mainMod .. " + mouse_up",          smw.cycle_workspaces("+1"))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("~/.config/hypr/scripts/volume.sh up"),   { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("~/.config/hypr/scripts/volume.sh down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("~/.config/hypr/scripts/volume.sh mute"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("~/.config/hypr/scripts/volume.sh mute"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),         { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),         { locked = true, repeating = true })
hl.bind("XF86Calculator",        hl.dsp.exec_cmd(V.calc),                                  { locked = true, repeating = true })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
