-- Generated by nwg-displays on 2026-07-19 at 17:51:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1600x0",
    scale = 1.0,
    mirror = "eDP-1"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1600x900@60.0",
    position = "0x0",
    scale = 1.0
})
