-- Generated by nwg-displays on 2026-06-02 at 20:06:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1600x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1600x900@60.0",
    position = "0x0",
    scale = 1.0
})
