$terminal = kitty
$fileManager = thunar
$menu = ~/.config/rofi/scripts/launcher_t1

# Add this line in ~/.config/brave-flags.conf
# --password-store=gnome-libsecret --ozone-platform-hint=auto --gtk-version=4 --disable-gpu-compositing
$browser = brave

$logout = command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
$screenshot = grim -g "$(slurp)" - | swappy -f -
$calc = ~/.local/bin/rofi-calc
$emoji = ~/.local/bin/rofi-emoji
$powermenu = ~/.config/rofi/scripts/powermenu_t3
$stickynotes= mkdir -p ~/Documents/NOTES && kitty --class mowland-stickynotes -e nvim ~/Documents/NOTES
$resetElecwhat = cat ~/.config/elecwhat/persistent-state.json | jq '."window-bounds"' | jq '{"window-bounds": {"x": 0, "y": 0, "width": .width, "height": .height}}' > ~/.config/elecwhat/persistent-state.json
