$terminal = kitty
$fileManager = thunar
$menu = ~/.config/rofi/scripts/launcher_t1
$browser = librewolf
$logout = command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
$screenshot = grim -g "$(slurp)" - | swappy -f -
$calc = ~/.local/bin/rofi-calc
$emoji = ~/.local/bin/rofi-emoji
