##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

windowrule {
    name = float-fdm
    match:class = fdm
    float = yes
}

windowrule {
    name = float-whatsapp
    match:class = elecwhat
    float = yes
}


windowrule {
    name = float-discord
    match:class = vesktop
    float = yes

    persistent_size = on
}

windowrule {
    name = browser-extension
    match:class = librewolf
    match:title = ^Extension

    float = yes
    persistent_size = on
}

windowrule {
    name = volume-control-float
    match:class = org.pulseaudio.pavucontrol

    float = yes
    persistent_size = on
}

windowrule {
    name = youtube-music-float
    match:class = com.github.th_ch.youtube_music

    float = yes
    persistent_size = on
    size = monitor_w/1.5 monitor_h/1.5
}

windowrule {
    name = float-blueman
    match:class = blueman-manager

    float = yes
    persistent_size = on
}

windowrule {
    name = float-btop
    match:class = floating_btop
    match:initial_class = floating_btop

    float = yes
    persistent_size = on
    size = monitor_w/1.5 monitor_h/1.15
}

windowrule {
    name = float-nmtui
    match:class = floating_nmtui
    match:initial_class = floating_nmtui

    float = yes
    persistent_size = on
    size = monitor_w/1.5 monitor_h/1.5
}

windowrule {
    name = float-thunar
    match:class = Thunar
    
    float = yes
    persistent_size = on
}

windowrule {
    name = sticky-notes
    match:class = mowland-stickynotes

    float = yes
    pin = yes
    size = 600 450
    move = monitor_w-625 monitor_h-480
}

